### PR TITLE
Enhance binaries report

### PR DESCRIPTION
**Pull request by topimiettinen**
Report also number of set-uid and set-gid binaries found.

Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

### CODE REVIEW

**Comment by Schmuuu** [comment]
Hi, 
What do you think about additional information in the "show details" to help the user figure out which binaries have these bits set?
I think about either listing the binaries, which might clutter the log or tell the user how he can find out himself which binaries are "affected".

**Comment by topimiettinen** [comment]
Good idea! I think similar things are logged elsewhere too.

**Comment by topimiettinen** [comment]
Updated with your suggestion.

I've been thinking about detecting non-PIE executables and other flags (execstack). The only decent tool I've found is Debian hardening-check, but it is very slow.

**Comment by topimiettinen** [comment]
Another idea for adding to `tests_hardening` could be to check if on a 64 bit system there are 32 bit libraries or if (on Linux) non-native binary types have been registered in `/proc/sys/fs/binfmt_misc`. The threat would be that the non-native emulations might be buggy.

**Comment by mboelen** [comment]
Thanks, merged the pull request. Made a small edit: call Report for each individual counter (instead of all on one line).

**Pull request merged**
