### PR TITLE
Add support for Solaris Image Packaging System (IPS)

### PR DESCRIPTION
**Pull request by Varbin**
IPS (Image Packaging System) is the new package system of Solaris 11.
This PR adds support for it.

New tests PKGS-7338 to -7341 detect this package manager, search for
updates and check if the support repository and patch metadata are
installed.

Additionally `pkg audit` is not detected wrongfully as audit tool any more.

### CODE REVIEW

**Comment by Varbin** [comment]
Setting this to draft. On Illumos based distributions, there is no support repository and the package manager might not be IPS (overview is here https://illumos.org/docs/about/distro/). I will open this PR once again after I have written added Illumos detection.

**Review by mboelen — CHANGES_REQUESTED** [review]
Thanks for your work. Some quick/small feedback while reviewing the code.
tail --> ${TAILBINARY}
$FIND --> ${FIND}
$(pkg .....) --> $(${PKGBINARY} .....)

**Comment by mboelen** [comment]
Another tip: add to the notes of the text that this is related to Solaris Image Packaging System (IPS). Not everyone is familiar with this abbreviation when it comes to packaging, especially if you have a security background :)

**Comment by Varbin** [comment]
> Not everyone is familiar with this abbreviation when it comes to packaging, especially if you have a security background :)

I have not idea how I have missed that, thank you for that hint ;)
To avoid writing out "Image Packaging System" on every test title (it is simply to long), it is written out only once, and further IPS tests are indentet.

```
[+] Ports and packages
------------------------------------
  - Searching package managers
    - Searching pkginfo                                       [ FOUND ]
    - Querying pkginfo for installed packages
    - Searching Image Packaging System (IPS = pkg(5))         [ FOUND ]
      - Querying for installed packages

  [WARNING]: Test PKGS-7338 had a long execution: 21 seconds

      - Checking for updates with IPS                         [ FOUND ]
      - Checking for support repository                       [ NOT FOUND ]
      - Checking for patch metadata                           [ NOT FOUND ]
```

(Regarding the long execution: IPS is somehow slow on my system).

If the first IPS test is skipped, there is now extra identation:

```
[+] Ports and packages
------------------------------------
  - Searching package managers
...
    - Checking for updates with IPS                         [ FOUND ]
    - Checking for support repository                       [ NOT FOUND ]
    - Checking for patch metadata                           [ NOT FOUND ]
```

> Some quick/small feedback while reviewing the code.

I think those are fixed with the last commits. As I rebased the commit to the latest master, Github lost the annotations.

**Pull request closed without merging**
