### PR TITLE
Update tests_firewalls -> FIRE-4508

### PR DESCRIPTION
**Pull request by teoberi**
Include #1554
Fix FIND variable (remove **"\n"** and **-z**)
Add sort + uniq while read line from FIND

### CODE REVIEW

**Comment by teoberi** [comment]
Whatever you want!
I tested the changes in Slackware and Ubuntu. It seems to me that they are OK, but you can also test.

**Comment by mboelen** [comment]
Thanks, changes merged.

**Comment by teoberi** [comment]
I haven't used NFQUEUE so I don't really know about it.
Maybe you can modify the output to get unique records, for example:
- Checking chain INPUT (table: filter, chain INPUT) [ NFQUEUE ]
I will test in the following days, now I am busy with another project.

**Comment by wileyhy** [comment]
Would it run faster like this?

if      [ "${table}" = "filter" ] ||
        [ "${table}" = "security" ]
then
        if      [ "${chain}" = "INPUT" ] &&
                [ "${target}" = "ACCEPT" ]
        then
                LogText "Result: Found ${target} for ${chain} (table:
${table})"
                Display --indent 6 --text "- Checking chain ${chain}
(table: ${table}, chain ${chain})" --result "${target}" --color YELLOW
                AddHP 1 3
        elif    [ "${chain}" = "INPUT" ] &&
                [ "${target}" = "DROP" ]
        then
                LogText "Result: Found ${target} for ${chain} (table:
${table})"
                Display --indent 6 --text "- Checking chain ${chain}
(table: ${table}, chain ${chain})" --result "${target}" --color GREEN
                AddHP 3 3
        elif    [ "${chain}" = "INPUT" ] ||
                [ "${chain}" = "FORWARD" ] ||
                [ "${chain}" = "OUTPUT" ]
        then
                if      [ "${target}" = "NFQUEUE" ]
                then
                        LogText "Result: Found ${target} for ${chain}
(table: ${table})"
                        Display --indent 6 --text "- Checking chain
${chain} (table: ${table}, chain ${chain})" --result "${target}" --color RED
                        ReportSuggestion "${TEST_NO}" "Consider avoid
${target} target if possible (iptables chain ${chain}, table: ${table})"
                        AddHP 0 3
                fi
        fi
fi

**Comment by teoberi** [comment]
The result for:

>  Checking iptables policies of chains [ FOUND ]

 should be ordered alphabetically (it's easier to find what you're looking for)
  
>  Checking chain INPUT (table: security, target: ACCEPT)  [ ACCEPT ]
>       Checking chain INPUT (table: filter, target: DROP)      [ DROP ]
>       Checking chain INPUT (table: filter, target: NFQUEUE)   [ NFQUEUE ]
>       Checking chain OUTPUT (table: filter, target: NFQUEUE)  [ NFQUEUE ]
 
The while do, if elif structure is extremely long for me.
You can make a pull request to see what others say.

**Pull request merged**
