### PR TITLE
Add PHP ini file locations for Ubuntu 18.04. Fix #628

### LINKED ISSUE #628: php 7.2 on ubuntu 18.04 only finding cli ini file.
**Describe the bug**
Trying out Lynis against Ubuntu 18.04 server and found that it finds the cli php .ini but not the apache2 one in /etc/php/7.2/apache2/php.ini

**Version**
 - Distribution Ubuntu 18.04
 - Lynis version 2.7.0

**Expected behavior**
Would expect /etc/php/7.2/apache2/php.ini to be included as it arguably more important than the CLI one.

**Additional context**
New to this tool / project.  I added the file to my local test_php, should I just do a pull request for the change to test_php.  :-)

### PR DESCRIPTION
**Pull request by NicolasCARPi**

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Hello,

Can someone have a look at this please?

Cheers,
~Nico

**Comment by mboelen** [comment]
Thanks Nicolas, it has been merged! It will be part of the upcoming release.

**Comment by NicolasCARPi** [comment]
Great, I was afraid that this project was dying. Glad to see it's active :)

**Comment by mboelen** [comment]
Alive and kicking :) The project had a lot of incoming pull requests, resulting in a backlog. So that is why it took a bit longer than we normally would like.

**Pull request merged**
