### PR TITLE
Fix multiple issues on Solaris 11

### LINKED ISSUE #1005: Lynis prints many errors and exceptions on Solaris
**Describe the bug**
Lynis detects Solaris correctly, it creates a lot of exceptions and behaves wrongly. For brevity, see at the log output below. 
My guess is that since Solaris 10 a lot of things changed.
Lynis also crashes on some locales, e.g. on de_DE.UTF-8, but de_DE.ISO8859-1 works.

**Version**
 - Solaris 11.4, x86 Edition; freshly installed
 - Lynis 7df0b86 (3.0.1)

**Expected behavior**
Lynis runs without errors and correctly works.

**Output**

Command output of `./lynis audit system` below, lynis-report.dat and lynis.log are [attached](https://github.com/CISOfy/lynis/files/5045424/lynis.zip).

<details>

```

[ Lynis 3.0.1 ]

################################################################################
  Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
  welcome to redistribute it under the terms of the GNU General Public License.
  See the LICENSE file for details about using this software.

  2007-2020, CISOfy - https://cisofy.com/lynis/
  Enterprise support available (compliance, plugins, interface and tools)
################################################################################


[+] Initializing program
------------------------------------
awk: syntax error near line 1
awk: bailing out near line 1
  - Detecting OS...                                           [ DONE ]
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
  - Checking profiles...                                      [ DONE ]

  ---------------------------------------------------
  Program version:           3.0.1
  Operating system:          Solaris
  Operating system name:     Sun Solaris
  Operating system version:  5.11
  Operating system mode:     64
  Kernel version:            
  Hardware platform:         i86pc
  Hostname:                  solaris
  ---------------------------------------------------
  Profiles:                  /root/lynis/default.prf
  Log file:                  /var/log/lynis.log
  Report file:               /var/log/lynis-report.dat
  Report version:            1.0
  Plugin directory:          ./plugins
  ---------------------------------------------------
  Auditor:                   [Not Specified]
  Language:                  en
  Test category:             all
  Test group:                all
  ---------------------------------------------------
  - Program update status...                                  [ NO UPDATE ]

[+] System Tools
------------------------------------
  - Scanning available tools...
  - Checking system binaries...
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .

[+] Plugins (phase 1)
------------------------------------
 Note: plugins have more extensive tests and may take several minutes to complete
  
  - Plugin: pam
-en     [
-en .
-en .
-en ]

  - Plugin: systemd
-en     [
-en .
-en .
-en .
-en .
-en .
-en .
-en .
-en .
-en .
-en .
-en .
-en .
-en .
-en .
-en .
-en .
-en ]


[+] Boot and services
------------------------------------
  - Service Manager                                           [ UNKNOWN ]
  - Checking presence GRUB2                                   [ FOUND ]
/usr/bin/find: stat() error /etc/grub.d: No such file or directory
    - Checking for password protection                        [ NONE ]

[+] Kernel
------------------------------------
  - Checking Solaris active kernel modules                    [ DONE ]

[+] Memory and Processes
------------------------------------
  - Querying prtconf for installed memory                     [ DONE ]

[+] Users, Groups and Authentication
------------------------------------
  - Administrator accounts                                    [ OK ]
  - Unique UIDs                                               [ OK ]
  - Consistency of group files (grpck)                        [ OK ]
  - Unique group IDs                                          [ OK ]
  - Unique group names                                        [ OK ]
  - Password file consistency                                 [ OK ]
awk: syntax error near line 1
awk: bailing out near line 1
  - Password hashing methods                                  [ OK ]
  - Query system users (non daemons)                          [ DONE ]
  - NIS+ authentication support                               [ NOT ENABLED ]
  - NIS authentication support                                [ NOT ENABLED ]
  - Sudoers file(s)                                           [ FOUND ]
    - Permissions for directory: /etc/sudoers.d               [ OK ]
    - Permissions for: /etc/sudoers                           [ OK ]
  - Passwordless accounts on Solaris                          [ OK ]
  - PAM password strength tools                               [ SUGGESTION ]
  - PAM configuration files (pam.conf)                        [ FOUND ]
  - PAM configuration files (pam.d)                           [ FOUND ]
  - PAM modules                                               [ NOT FOUND ]
  - LDAP module in PAM                                        [ NOT FOUND ]
awk: syntax error near line 1
awk: bailing out near line 1
  - Checking expired passwords                                [ OK ]
  - Checking Solaris /etc/default/sulogin file                [ OK ]
  - Determining default umask
    - umask (/etc/profile)                                    [ NOT FOUND ]
  - Checking account locking                                  [ NOT ENABLED ]
  - LDAP authentication support                               [ NOT ENABLED ]
awk: syntax error near line 1
awk: bailing out near line 1

[+] Shells
------------------------------------
  - Checking shells from /etc/shells
    Result: found 39 shells (valid shells: 38).
    - Session timeout settings/tools                          [ NONE ]
  - Checking default umask values
    - Checking default umask in /etc/profile                  [ NONE ]

[+] File systems
------------------------------------
  - Checking mount points
awk: syntax error near line 1
awk: bailing out near line 1
    - Checking /home mount point                              [ SUGGESTION ]
awk: syntax error near line 1
awk: bailing out near line 1
    - Checking /tmp mount point                               [ SUGGESTION ]
awk: syntax error near line 1
awk: bailing out near line 1
    - Checking /var mount point                               [ SUGGESTION ]
  - Checking for old files in /tmp                            [ OK ]
  - Checking /tmp sticky bit                                  [ OK ]
  - Checking /var/tmp sticky bit                              [ OK ]

[+] USB Devices
------------------------------------

[+] Storage
------------------------------------

[+] NFS
------------------------------------
  - Query rpc registered programs                             [ DONE ]
  - Query NFS versions                                        [ DONE ]
  - Query NFS protocols                                       [ DONE ]
  - Check running NFS daemon                                  [ NOT FOUND ]

[+] Name services
------------------------------------
  - Checking default DNS search domain                        [ FOUND ]
  - Checking uname -n output                                  [ DONE ]
  - Checking /etc/nodename                                    [ NONE FOUND ]
  - Searching DNS domain name                                 [ FOUND ]
      Domain name: fritz.box
  - Checking nscd status                                      [ RUNNING ]
  - Checking /etc/hosts
    - Duplicate entries in hosts file                         [ NONE ]
    - Presence of configured hostname in /etc/hosts           [ FOUND ]
    - Hostname mapped to localhost                            [ NOT FOUND ]
    - Localhost mapping to IP address                         [ OK ]

[+] Ports and packages
------------------------------------
  - Searching package managers
    - Searching pkginfo                                       [ FOUND ]
    - Querying pkginfo for installed packages
  - Checking package audit tool                               [ INSTALLED ]
    Found: pkg audit

[+] Networking
------------------------------------
  - Hostname (allowed characters)                             [ WARNING ]
  - Checking configured nameservers
    - Testing nameservers
        Nameserver: 10.0.2.3                                  [ OK ]
    - Minimal of 2 responsive nameservers                     [ WARNING ]
  - Checking default gateway                                  [ DONE ]
awk: syntax error near line 1
awk: bailing out near line 1

=================================================================

  Exception found!

  Function/test:  [NETW-3004:1]
  Message:        No interfaces found on this system (OS=Solaris)

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (./lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================


=================================================================

  Exception found!

  Function/test:  [NETW-3012:2]
  Message:        Unclear what method to use, to determine listening port information

  Help improving the Lynis community with your feedback!

  Steps:
  - Ensure you are running the latest version (./lynis update check)
  - If so, create a GitHub issue at https://github.com/CISOfy/lynis
  - Include relevant parts of the log file or configuration file

  Thanks!

=================================================================

  - Getting listening ports (TCP/UDP)                         [ SKIPPED ]
  - Checking waiting connections                              [ OK ]
  - Checking status DHCP client                               [ NOT ACTIVE ]

[+] Printers and Spools
------------------------------------
  - Checking cups daemon                                      [ RUNNING ]
  - Checking CUPS configuration file                          [ OK ]
    - File permissions                                        [ OK ]
  - Checking CUPS addresses/sockets                           [ FOUND ]
  - Checking lp daemon                                        [ NOT RUNNING ]

[+] Software: e-mail and messaging
------------------------------------
  - Sendmail status                                           [ RUNNING ]

[+] Software: firewalls
------------------------------------
  - Checking host based firewall                              [ NOT ACTIVE ]

[+] Software: webserver
------------------------------------
  - Checking Apache                                           [ NOT FOUND ]
  - Checking nginx                                            [ NOT FOUND ]

[+] SSH Support
------------------------------------
  - Checking running SSH daemon                               [ FOUND ]
    - Searching SSH configuration                             [ FOUND ]
awk: syntax error near line 1
awk: illegal statement near line 1
awk: syntax error near line 1
awk: bailing out near line 1
    - OpenSSH option: AllowUsers                              [ NOT FOUND ]
    - OpenSSH option: AllowGroups                             [ NOT FOUND ]

[+] SNMP Support
------------------------------------
  - Checking running SNMP daemon                              [ NOT FOUND ]

[+] Databases
------------------------------------
    No database engines found

[+] LDAP Services
------------------------------------
  - Checking OpenLDAP instance                                [ NOT FOUND ]

[+] PHP
------------------------------------
  - Checking PHP                                              [ NOT FOUND ]

[+] Squid Support
------------------------------------
  - Checking running Squid daemon                             [ NOT FOUND ]

[+] Logging and files
------------------------------------
  - Checking for a running log daemon                         [ OK ]
    - Checking Syslog-NG status                               [ NOT FOUND ]
    - Checking systemd journal status                         [ NOT FOUND ]
    - Checking Metalog status                                 [ NOT FOUND ]
    - Checking RSyslog status                                 [ NOT FOUND ]
    - Checking RFC 3195 daemon status                         [ NOT FOUND ]
  - Checking loghost entry                                    [ OK ]
  - Checking remote logging                                   [ ENABLED ]
  - Checking log directories (static list)                    [ DONE ]
  - Checking open log files                                   [ SKIPPED ]

[+] Insecure services
------------------------------------
  - Installed inetd package                                   [ NOT FOUND ]
    - Checking enabled inetd services                         [ OK ]
  - Installed xinetd package                                  [ OK ]
    - xinetd status                                           [ NOT ACTIVE ]
  - Installed rsh client package                              [ OK ]
  - Installed rsh server package                              [ OK ]
  - Installed telnet client package                           [ OK ]
  - Installed telnet server package                           [ NOT FOUND ]
  - Checking NIS client installation                          [ OK ]
  - Checking NIS server installation                          [ OK ]
  - Checking TFTP client installation                         [ OK ]
  - Checking TFTP server installation                         [ OK ]

[+] Banners and identification
------------------------------------
  - /etc/issue                                                [ NOT FOUND ]
  - /etc/issue.net                                            [ NOT FOUND ]

[+] Scheduled tasks
------------------------------------
/usr/bin/egrep: illegal option -- q
usage: egrep [ -bchilnsv ] [ -e exp ] [ -f file ] [ strings ] [ file ] ...
/usr/bin/egrep: illegal option -- q
usage: egrep [ -bchilnsv ] [ -e exp ] [ -f file ] [ strings ] [ file ] ...
/usr/bin/egrep: illegal option -- q
usage: egrep [ -bchilnsv ] [ -e exp ] [ -f file ] [ strings ] [ file ] ...
  - Checking crontab and cronjob files                        [ WARNING ]

[+] Accounting
------------------------------------
  - Checking Solaris audit daemon status                      [ RUNNING ]
    - Checking Solaris audit daemon status                    [ ONLINE ]
    - Checking Solaris BSM (/etc/system)                      [ NOT FOUND ]
    - Checking Solaris BSM (modules list)                     [ ENABLED ]
    - Checking Solaris audit location                         [ SKIPPED ]
    - Checking Solaris audit statistics                       [ DONE ]

[+] Time and Synchronization
------------------------------------
  - Checking for a running NTP daemon or client               [ WARNING ]

[+] Cryptography
------------------------------------
  - Checking for expired SSL certificates [0/0]               [ NONE ]

[+] Virtualization
------------------------------------

[+] Containers
------------------------------------
  - Checking Solaris Zones                                    [ NONE ]

[+] Security frameworks
------------------------------------
  - Checking presence AppArmor                                [ NOT FOUND ]
  - Checking presence SELinux                                 [ NOT FOUND ]
  - Checking presence TOMOYO Linux                            [ NOT FOUND ]
  - Checking presence grsecurity                              [ NOT FOUND ]
  - Checking for implemented MAC framework                    [ NONE ]

[+] Software: file integrity
------------------------------------
  - Checking file integrity tools
  - Checking presence integrity tool                          [ NOT FOUND ]

[+] Software: System tooling
------------------------------------
  - Checking automation tooling
  - Automation tooling                                        [ NOT FOUND ]
  - Checking for IDS/IPS tooling                              [ NONE ]

[+] Software: Malware
------------------------------------

[+] File Permissions
------------------------------------
  - Starting file permissions check
awk: syntax error near line 1
awk: illegal statement near line 1
    File: /boot/grub/grub.cfg                                 [ SUGGESTION ]
awk: syntax error near line 1
awk: illegal statement near line 1
    File: /etc/group                                          [ SUGGESTION ]
awk: syntax error near line 1
awk: illegal statement near line 1
    File: /etc/motd                                           [ SUGGESTION ]
awk: syntax error near line 1
awk: illegal statement near line 1
    File: /etc/passwd                                         [ SUGGESTION ]
awk: syntax error near line 1
awk: illegal statement near line 1
    File: /etc/ssh/sshd_config                                [ SUGGESTION ]
awk: syntax error near line 1
awk: illegal statement near line 1
    Directory: /etc/cron.d                                    [ SUGGESTION ]

[+] Home directories
------------------------------------
awk: syntax error near line 1
awk: illegal statement near line 1
awk: syntax error near line 1
awk: bailing out near line 1
  - Permissions of home directories                           [ OK ]
awk: syntax error near line 1
awk: bailing out near line 1
  - Ownership of home directories                             [ OK ]
  - Checking shell history files                              [ SKIPPED ]

[+] Kernel Hardening
------------------------------------

[+] Hardening
------------------------------------
    - Installed compiler(s)                                   [ FOUND ]
    - Installed malware scanner                               [ NOT FOUND ]

[+] Custom tests
------------------------------------
  - Running custom tests...                                   [ NONE ]

[+] Plugins (phase 2)
------------------------------------
  - Plugins (phase 2)                                         [ DONE ]

================================================================================

  -[ Lynis 3.0.1 Results ]-

  Warnings (4):
  ----------------------------
  ! No vulnerability database available [PKGS-7381] 
    - Details  : pkg audit
    - Solution : Run pkg audit -F
      https://cisofy.com/lynis/controls/PKGS-7381/

  ! Hostname contains invalid characters [NETW-2400] 
    - Details  : hostname
    - Solution : See log file for invalid characters
      https://cisofy.com/lynis/controls/NETW-2400/

  ! Couldn't find 2 responsive nameservers [NETW-2705] 
      https://cisofy.com/lynis/controls/NETW-2705/

  ! Found one or more cronjob files with incorrect ownership (see log for details) [SCHD-7704] 
      https://cisofy.com/lynis/controls/SCHD-7704/

  Suggestions (14):
  ----------------------------
  * Set a password on GRUB boot loader to prevent altering boot configuration (e.g. boot in single user mode without password) [BOOT-5122] 
      https://cisofy.com/lynis/controls/BOOT-5122/

  * Install a PAM module for password strength testing like pam_cracklib or pam_passwdqc [AUTH-9262] 
      https://cisofy.com/lynis/controls/AUTH-9262/

  * To decrease the impact of a full /home file system, place /home on a separate partition [FILE-6310] 
      https://cisofy.com/lynis/controls/FILE-6310/

  * To decrease the impact of a full /tmp file system, place /tmp on a separate partition [FILE-6310] 
      https://cisofy.com/lynis/controls/FILE-6310/

  * To decrease the impact of a full /var file system, place /var on a separate partition [FILE-6310] 
      https://cisofy.com/lynis/controls/FILE-6310/

  * Check your resolv.conf file and fill in a backup nameserver if possible [NETW-2705] 
      https://cisofy.com/lynis/controls/NETW-2705/

  * Check CUPS configuration if it really needs to listen on the network [PRNT-2308] 
      https://cisofy.com/lynis/controls/PRNT-2308/

  * Configure a firewall/packet filter to filter incoming and outgoing traffic [FIRE-4590] 
      https://cisofy.com/lynis/controls/FIRE-4590/

  * Use NTP daemon or NTP client to prevent time issues. [TIME-3104] 
      https://cisofy.com/lynis/controls/TIME-3104/

  * Install a file integrity tool to monitor changes to critical and sensitive files [FINT-4350] 
      https://cisofy.com/lynis/controls/FINT-4350/

  * Determine if automation tools are present for system management [TOOL-5002] 
      https://cisofy.com/lynis/controls/TOOL-5002/

  * Consider restricting file permissions [FILE-7524] 
    - Details  : See screen output or log file
    - Solution : Use chmod to change file permissions
      https://cisofy.com/lynis/controls/FILE-7524/

  * Harden compilers like restricting access to root user only [HRDN-7222] 
      https://cisofy.com/lynis/controls/HRDN-7222/

  * Harden the system by installing at least one malware scanner, to perform periodic file system scans [HRDN-7230] 
    - Solution : Install a tool like rkhunter, chkrootkit, OSSEC
      https://cisofy.com/lynis/controls/HRDN-7230/

  Follow-up:
  ----------------------------
  - Show details of a test (lynis show details TEST-ID)
  - Check the logfile for all details (less /var/log/lynis.log)
  - Read security controls texts (https://cisofy.com)
  - Use --upload to upload data to central system (Lynis Enterprise users)

================================================================================

  Lynis security scan details:

  Hardening index : 53 [##########          ]
  Tests performed : 184
  Plugins enabled : 2

  Components:
  - Firewall               [X]
  - Malware scanner        [X]

  Scan mode:
  Normal [V]  Forensics [ ]  Integration [ ]  Pentest [ ]

  Lynis modules:
  - Compliance status      [?]
  - Security audit         [V]
  - Vulnerability scan     [V]

  Files:
  - Test and debug information      : /var/log/lynis.log
  - Report data                     : /var/log/lynis-report.dat

================================================================================

  Exceptions found
  Some exceptional events or information was found!

  What to do:
  You can help by providing your log file (/var/log/lynis.log).
  Go to https://cisofy.com/contact/ and send your file to the e-mail address listed

================================================================================

  Lynis 3.0.1

  Auditing, system hardening, and compliance for UNIX-based systems
  (Linux, macOS, BSD, and others)

  2007-2020, CISOfy - https://cisofy.com/lynis/
  Enterprise support available (compliance, plugins, interface and tools)

================================================================================

  [TIP]: Enhance Lynis audits by adding your settings to custom.prf (see /root/lynis/default.prf for all settings)

grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
grep: illegal option -- E
Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
```

</details>

On Solaris, the default *grep* does not accept -E, only /usr/xpg4/bin/grep, the same with *egrep* and the -q option.

### PR DESCRIPTION
**Pull request by Varbin**
Fixes #1005. Below is a list of of changes and solved problems:
 
 - Issues with grep and egrep are fixed
 - Use GNU echo for echo -n or printf and nawk instead of awk
 - Include support for Solaris netstat: 
 - Fix check for existence of grub.d
 - Do hostname checking in two steps, as Solaris' tr does not support full regular expressions
 - Test if loghost is not localhost and remote logging to remote localhost loghost is not detected as remote logging (LOGG-2153)
 - Support for Solaris' 11 package manager:
   -  `pkg audit` is not falsely detected as package audit software
   - Support repository installation is tested (equivalent to security repository on Debian, but one has to buy access)
   - Detect solaris-11-cpu as audit tool (vulnerability database for IPS / pkg), it requires the to the support repository
   - Other tests as package enumeration, available updates, ...
   - New tests: PKGS-7338, PKGS-7339, PKGS-7340, PKGS-7341
 - Detect sshd at the uncommon Solaris location and fix the awk operation not supported on Solaris, so the configuration check was skipped.
 - Detect IPS service manager (or SysV) in  BOOT-5170 (new). The SysV permission test BOOT-5184 is executed on Solaris.
 - Detect Trusted Solaris as MAC framework (new tests MACF-6250 and MACF-6252). Linux MAC and RBAC framework tests are now only executed on Linux.

Open issues:
 - Ownership problems: Solaris uses different permissions than most other Unix systems. The "classic" bin, sys, ... groups are still used and and can be checked with pkg verify. I don't think this can only solved with support for os specific permission tests.

### CODE REVIEW

**Comment by Varbin** [comment]
@mboelen 
Shouldn't nawk be used everywhere? Usually awk is either nawk or gawk (and even nawk may be gawk), but I don't think this is guaranteed to be (as seen on Solaris) everywhere.

**Comment by Varbin** [comment]
@mboelen Are there any problems with this PR?

**Comment by mboelen** [comment]
Hi @Varbin - Thanks for your work on this. The pull request is currently too big to review and therefore merge.

For example, we moved away from `egrep` to `grep -E` as the first is considered to be deprecated: 

> In addition, two variant programs egrep and fgrep are available. egrep is the same as ‘grep -E’. fgrep is the same as ‘grep -F’. Direct invocation as either egrep or fgrep is deprecated, but is provided to allow historical applications that rely on them to run unmodified.

Source: [GNU grep man page](https://www.gnu.org/software/grep/manual/grep.html)

Also, `grep -E` seems to be supported by most operating systems, even Solaris (with /usr/xpg4/bin/grep). So I think the issue is not in the usage of `grep -E`, but that Lynis might not use the right grep binary on Solaris.

So I would love to get your great work on this implemented, but that is only possible if we can do it in small steps (read: multiple pull requests). This way everything can be reviewed properly, then quickly merged.

**Comment by Varbin** [comment]
@mboelen I will split it in smaller pull requests.

**Comment by mboelen** [comment]
Thanks :)

**Pull request closed without merging**
