### PR TITLE
Update functions

### PR DESCRIPTION
**Pull request by Slydder**
Fix for apache config file names with special characters.

### CODE REVIEW

**Comment by quantumpacket** [comment]
@Slydder Shouldn't those be double quotes? Otherwise you are having it check the literal string `${sFILE}` and not the value of that variable. https://www.gnu.org/software/bash/manual/html_node/Quoting.html#Quoting

**Comment by Slydder** [comment]
attached you will find a working version. changes include:

1. I added a new variable to escape '*' and '?' characters in the file name
2. changed the '-L' tests in the if statements (which doesn't work with escaped characters for some reason) to '-h' which seems to work
3. changed the ls -d -l calls in the if statements to stat -c %A which work with escaped characters

[functions.zip](https://github.com/CISOfy/lynis/files/689775/functions.zip)

**Comment by mboelen** [comment]
Thanks for the pull request, very much appreciated!

The stat command is not available on all platforms (like AIX). So currently this patch would break core functionality and needs a little bit more rework to get accepted.

**Comment by mboelen** [comment]
Manually picked some of the changes from this pull request. As said, the stat command is not working the same on all platforms. Thanks for your contribution!

**Pull request closed without merging**
