### PR TITLE
[KRNL-6000] Check more sysctls

### PR DESCRIPTION
**Pull request by topimiettinen**
Add checks for sysctls recommended by CLIP OS (vanilla kernel sysctls
only):
https://docs.clip-os.org/clipos/kernel.html#sysctl-security-tuning

Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

### CODE REVIEW

**Comment by topimiettinen** [comment]
@mboelen The sysctl which prevents module loading may need some nontrivial work on behalf of the administrator especially if the hardware of the system is allowed to change (like inserting various USB stuff). It will greatly decrease attack surface, so it should be worth the effort. 

Other sysctls should be relatively harmless to enable. I haven't seen any issues.

**Comment by topimiettinen** [comment]
@mboelen Sadly the bot has closed all my PRs #911, #914, #905, #926 and #936 because of inactivity. It seems that my contributions are not welcome anymore.

**Comment by mboelen** [comment]
Thanks, merged!

Your contributions are still very welcome. I will check the closed PRs and reopen them. My apologies for the unintended closure. The bot is pretty binary when it comes to closing things.

**Comment by quantumpacket** [comment]
> The bot is pretty binary when it comes to closing things.

@mboelen Can the bot be disabled from auto-closing PRs and issues? It's better to have them left open, than to have them erroneously closed.

**Comment by mboelen** [comment]
@quantumpacket I looked at that during activation, but the bot has no fine-grained configuration :(

**Pull request merged**
