### PR TITLE
FIRE-4508 - Enhancements

### PR DESCRIPTION
**Pull request by nser77**
Hello, this PR fixes the FIRE-4508 control and adds  the following features:

- Deep parsing of `iptables` output with no dependencies.
- If the `sort` binary is present, the output includes only unique records; otherwise, it includes the raw results.
- Control if `NFQUEUE` target is present only in the security and filter tables.

iptables:

```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -j NFQUEUE --queue-num 0 --queue-bypass
-A INPUT -j NFQUEUE --queue-num 1 --queue-bypass
```

Results:

```
[+] Software: firewalls
------------------------------------
  - Checking iptables kernel module                           [ FOUND ]
    - Checking iptables policies of chains                    [ FOUND ]
      - Checking chain INPUT (table: filter, target: ACCEPT)  [ ACCEPT ]
      - Checking chain INPUT (table: filter, target: NFQUEUE)  [ NFQUEUE ]
      - Checking chain INPUT (table: security, target: ACCEPT)  [ ACCEPT ]
    - Checking for empty ruleset                              [ WARNING ]
    - Checking for unused rules                               [ FOUND ]
  - Checking host based firewall                              [ ACTIVE ]

  Suggestions:
  ----------------------------

  * Consider avoid NFQUEUE target if possible (iptables chain INPUT, table: filter) [FIRE-4508]
      https://cisofy.com/lynis/controls/FIRE-4508/

  * Check iptables rules to see which rules are currently not used [FIRE-4513]
      https://cisofy.com/lynis/controls/FIRE-4513/

```

Please provide feedbacks!

Regards,

### CODE REVIEW

**Comment by teoberi** [comment]
It doesn't work for my firewall!

> /lynis/include/tests_firewalls: line 177: shift: 4: shift count out of range

**Comment by teoberi** [comment]
> /lynis/include/tests_firewalls: line 178: shift: 4: shift count out of range

Test the changes with a real, production firewall.

**Comment by wileyhy** [comment]
Something on style:

From CONTRIBUTING.md:

"Variables should be capitalized, with underscore as word separator (e.g.
PROCESS_EXISTS=1)."

**Comment by mboelen** [comment]
Thanks for the great work on this! I got a few suggestions:

- I support the remark made by @wileyhy about using the right variable name structure. Also, try to give it a clear name, preferably with a temporary variable name, something like `t` could become IPTABLES_TABLE. Then at the end of the table, unset the temporary variables. So please rename the variables and then use an 'unset IPTABLES_VAR1 IPTABLES_VAR` at the end of the test.
- Use long-format options when possible, as this makes it easier for people to read what a command does. For example `--list-rules` is better than `-S`, as it clearly states that it is showing rules.
- Did you test with another shell or using shellcheck? We want to avoid 'bashism'.

After those changes, I feel things can be merged and tested by the community.

**Comment by teoberi** [comment]
[ShellCheck](https://www.shellcheck.net/) finds some problems  for FIRE-4508  and offers suggestions for solving them.

**Comment by teoberi** [comment]
> /lynis/include/tests_firewalls: line 183: shift: 4: shift count out of range

**Comment by teoberi** [comment]
Now it works but I think you should eliminate duplicates.

> [+] Software: firewalls
------------------------------------
  - Checking iptables kernel module                           [ FOUND ]
    - Checking iptables policies of chains                    [ FOUND ]
 - Checking chain INPUT (table: filter, target: ACCEPT)  [ ACCEPT ]
      - Checking chain INPUT (table: filter, target: DROP)    [ DROP ]
      - Checking chain INPUT (table: filter, target: DROP)    [ DROP ]
      - Checking chain INPUT (table: filter, target: ACCEPT)  [ ACCEPT ]
      - Checking chain INPUT (table: filter, target: ACCEPT)  [ ACCEPT ]
      - Checking chain INPUT (table: filter, target: DROP)    [ DROP ]
      - Checking chain INPUT (table: filter, target: DROP)    [ DROP ]
...

**Comment by teoberi** [comment]
Now output it looks OK!

```
[+] Software: firewalls
------------------------------------
  - Checking iptables kernel module                           [ FOUND ]
    - Checking iptables policies of chains                    [ FOUND ]
      - Chain INPUT (table: filter, target: ACCEPT)           [ ACCEPT ]
      - Chain INPUT (table: filter, target: DROP)             [ DROP ]
      - Chain INPUT (table: security, target: ACCEPT)         [ ACCEPT ]
    - Checking for empty ruleset                              [ OK ]
    - Checking for unused rules                               [ FOUND ]
  - Checking host based firewall                              [ ACTIVE ]
```
In lynis.log I don't know, you have to check if that's what you want.

>024-10-16 10:03:11 ==== 
2024-10-16 10:03:11 Performing test ID FIRE-4508 (Check used policies of iptables chains)
2024-10-16 10:03:11 Hardening: assigned partial number of hardening points (1 of 3). Currently having 121 points (out of 177)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 124 points (out of 180)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 127 points (out of 183)
2024-10-16 10:03:11 Hardening: assigned partial number of hardening points (1 of 3). Currently having 128 points (out of 186)
2024-10-16 10:03:11 Hardening: assigned partial number of hardening points (1 of 3). Currently having 129 points (out of 189)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 132 points (out of 192)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 135 points (out of 195)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 138 points (out of 198)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 141 points (out of 201)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 144 points (out of 204)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 147 points (out of 207)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 150 points (out of 210)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 153 points (out of 213)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 156 points (out of 216)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 159 points (out of 219)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 162 points (out of 222)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 165 points (out of 225)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 168 points (out of 228)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 171 points (out of 231)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 174 points (out of 234)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 177 points (out of 237)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 180 points (out of 240)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 183 points (out of 243)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 186 points (out of 246)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 189 points (out of 249)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 192 points (out of 252)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 195 points (out of 255)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 198 points (out of 258)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 201 points (out of 261)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 204 points (out of 264)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 207 points (out of 267)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 210 points (out of 270)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 213 points (out of 273)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 216 points (out of 276)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 219 points (out of 279)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 222 points (out of 282)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 225 points (out of 285)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 228 points (out of 288)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 231 points (out of 291)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 234 points (out of 294)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 237 points (out of 297)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 240 points (out of 300)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 243 points (out of 303)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 246 points (out of 306)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 249 points (out of 309)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 252 points (out of 312)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 255 points (out of 315)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 258 points (out of 318)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 261 points (out of 321)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 264 points (out of 324)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 267 points (out of 327)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 270 points (out of 330)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 273 points (out of 333)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 276 points (out of 336)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 279 points (out of 339)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 282 points (out of 342)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 285 points (out of 345)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 288 points (out of 348)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 231 points (out of 291)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 234 points (out of 294)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 237 points (out of 297)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 240 points (out of 300)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 243 points (out of 303)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 246 points (out of 306)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 249 points (out of 309)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 252 points (out of 312)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 255 points (out of 315)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 258 points (out of 318)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 261 points (out of 321)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 264 points (out of 324)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 267 points (out of 327)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 270 points (out of 330)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 273 points (out of 333)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 276 points (out of 336)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 279 points (out of 339)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 282 points (out of 342)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 285 points (out of 345)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 288 points (out of 348)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 291 points (out of 351)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 294 points (out of 354)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 297 points (out of 357)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 300 points (out of 360)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 303 points (out of 363)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 306 points (out of 366)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 309 points (out of 369)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 312 points (out of 372)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 315 points (out of 375)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 318 points (out of 378)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 321 points (out of 381)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 324 points (out of 384)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 327 points (out of 387)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 330 points (out of 390)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 333 points (out of 393)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 336 points (out of 396)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 339 points (out of 399)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 342 points (out of 402)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 345 points (out of 405)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 348 points (out of 408)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 351 points (out of 411)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 354 points (out of 414)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 357 points (out of 417)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 360 points (out of 420)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 363 points (out of 423)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 366 points (out of 426)
2024-10-16 10:03:11 Hardening: assigned maximum number of hardening points for this item (3). Currently having 369 points (out of 429)
2024-10-16 10:03:11 Hardening: assigned partial number of hardening points (1 of 3). Currently having 370 points (out of 432)
2024-10-16 10:03:11 Hardening: assigned partial number of hardening points (1 of 3). Currently having 371 points (out of 435)
2024-10-16 10:03:11 Hardening: assigned partial number of hardening points (1 of 3). Currently having 372 points (out of 438)
2024-10-16 10:03:11 Info: sorting output
2024-10-16 10:03:11 Result: Found target 'ACCEPT' for chain 'INPUT' (table: filter)
2024-10-16 10:03:11 Result: Found target 'DROP' for chain 'INPUT' (table: filter)
2024-10-16 10:03:11 Info: sorting output
2024-10-16 10:03:12 Info: sorting output
2024-10-16 10:03:12 Info: sorting output
2024-10-16 10:03:12 Hardening: assigned partial number of hardening points (1 of 3). Currently having 121 points (out of 177)
2024-10-16 10:03:12 Info: sorting output
2024-10-16 10:03:12 Result: Found target 'ACCEPT' for chain 'INPUT' (table: security)
2024-10-16 10:03:12 ====

**Comment by teoberi** [comment]
We can continue the discussion in the new PR.

**Pull request merged**
