### PR TITLE
fix issue #620

### PR DESCRIPTION
**Pull request by Capashenn**
fix issue #620

### CODE REVIEW

**Comment by mboelen** [comment]
This patch uses bash shell scripting instead of POSIX-safe script. For that reason, it can't be merged.

`if case ${AIDE_DB} in @@*) ;; *) false;; esac;`

**Comment by Capashenn** [comment]
Could you explain to me where the bashism is ?

I carrefully read the [POSIX specification](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html) and didn't find anything relevent

I tested the script with dash and it worked perfectly well.
Moreover, i used `checkbashisms `and no error reported.

**Comment by mboelen** [comment]
My apologies, you are right, this is valid code. The `@@*` and `false` looked unusual to me.

**Comment by mboelen** [comment]
Closing, see remark on related issue https://github.com/CISOfy/lynis/issues/611

**Pull request closed without merging**
