### PR TITLE
Issue 1338

### PR DESCRIPTION
**Pull request by xnoguer**
I replaced all uses of egrep in order to solve issue #1338.
I few notes:
- Also changed to grep -E in cases where there didn't seem to be necessary (for instance KRNL-5788).
- Replacements in tests_tooling and tests_insecure_services were in commented code.
- Run the modified code in a couple of distributions that don't include egrep: archlinux, fedora:latest. Also run in a couple of linux distributions that do include egrep, without errors. I'm attaching the result of tests, and if I can test in any other OS in the next few days I'll add the results of those tests.

[issue_1338_tests.ods](https://github.com/CISOfy/lynis/files/11305219/issue_1338_tests.ods)

### CODE REVIEW

**Comment by limburgher** [comment]
This works great on Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=2211893, though with a few errors. Attaching build log of local test.
[build.log](https://github.com/CISOfy/lynis/files/11838133/build.log)

**Comment by mboelen** [comment]
Thanks, merged!

**Comment by limburgher** [comment]
Still seeing some egrep errors.

**Comment by xnoguer** [comment]
@limburgher Can you test #1438 ? It gets rid of the warning you reported.

**Comment by limburgher** [comment]
It does indeed, thank you!

**Pull request merged**
