### PR TITLE
Check IMA/EVM, dm-integrity and dm-verity statuses

### PR DESCRIPTION
**Pull request by topimiettinen**
Check for evmctl (Extended Verification Module) tool and system IMA (Integrity Measurement
Architecture) status.

Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

### CODE REVIEW

**Comment by topimiettinen** [comment]
I was also thinking about checks for integritysetup and veritysetup (which are probably more popular than IMA/EVM), but I don't have an idea how to find out if they are used. They could be installed as part of a bigger package (cryptsetup), so just the presence of the tools does not tell much.

**Comment by topimiettinen** [comment]
Wasn't so hard after all. I put this commit on top of EVM/IMA commit to avoid merge conflicts.

**Comment by mboelen** [comment]
Thanks, merged!

**Comment by mboelen** [comment]
Looks like a file was missing. Made commit https://github.com/CISOfy/lynis/commit/603d5b16a282b6c2f646bae450002e385bd91b3f

@topimiettinen Is it correct this way?

**Pull request merged**
