### PR TITLE
Add NixOS and IPFire

### LINKED ISSUE #1040: Unknown OS found in /etc/os-releases on IPFire 2.25 (x86_64) - core150
**Describe the bug**
Exception found! [OS DETECTION]

**Version**
 - Distribution [IPFire 2.25 (x86_64)]
 - Lynis version [3.0.2]

**Expected behavior**

**Output**

**Additional context**
$ cat /etc/os-release

NAME="IPFire"
VERSION="2.25"
ID=ipfire
VERSION_ID=2
PRETTY_NAME="IPFire 2.25 (x86_64) - core150"
ANSI_COLOR="0:31"

_Note : IPFire (open firewall solution) supports the work of **lynis** - addon in IPFire > Pakfire addons list_

### LINKED ISSUE #1068: Unknown OS found in /etc/os-releases on NixOS
**Describe the bug**
An exception message is printed complaining of an unknown OS.

**Version**
 - Distribution NixOS 20.03
 - Lynis version 3.0.1

**Expected behavior**
No such warning.

**Output**
Unknown OS found in /etc/os-release - Please create issue on GitHub project page: https://github.com/CISOfy/lynis

**Additional context**

```sh
$ cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="20.03.3158.7c2a362b58a (Markhor)"
VERSION_CODENAME=markhor
VERSION_ID="20.03.3158.7c2a362b58a"
PRETTY_NAME="NixOS 20.03 (Markhor)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

### PR DESCRIPTION
**Pull request by Varbin**
Fixes #1040 and fixes #1068.

### CODE REVIEW

**Comment by Varbin** [comment]
@ryneeverett @steph78630 Do you mind testing if this fixes your issues?

**Comment by steph78630** [comment]
Hi @Varbin ,

It works perfectly with IPFire !!! :-)

thank you for your work !

**Comment by ryneeverett** [comment]
Works great on NixOS, thanks!

**Comment by mboelen** [comment]
Looks good, merged!

**Pull request merged**
